###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

# Just an example use case
# enable_analytics: no
_site_root: /hudson_woods/statamic/
_site_url: ~philippe/hudson_woods/statamic/